name: wolf_jobs
description: Wolf Jobs Platform helps you find local jobs in events, healthcare and other industries in and around New York City. 


#version: 1.0.0+1
version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  random_pk: any  
  pusher_websocket_flutter: 0.2.0
  shimmer: ^1.0.1
  transparent_image: ^0.1.0
  flutter_slidable: ^0.4.9
  flutter_rating: ^0.0.2
  lottie: ^0.4.0+1
  html: ^0.14.0+3
  giffy_dialog: ^1.3.0
  auto_size_text: ^2.1.0 
  sticky_headers:
  collection: ^1.14.11
  shared_preferences:
  http: ^0.12.0+2
  json_serializable: ^3.2.3
  #  scoped_model: ^0.3.0
  fluttertoast: 4.0.1
  toast: ^0.1.5
  onesignal_flutter: ^2.6.1
  google_maps_flutter: ^0.5.21+15
  #notification_permissions: ^0.4.4
  permission_handler: 5.0.1+1
  maps_launcher: ^1.2.0  
  flushbar:        
  #flushbar:
  #  git:
  #    url: git://github.com/valterh4ck3r/flushbar
  #    ref: master
  cupertino_back_gesture: ^0.0.2
  cached_network_image: ^2.0.0
  flutter_cupertino_date_picker: ^1.0.12
  image_picker: ^0.6.3+3
  intl: ^0.16.0
  dio: ^3.0.9
  flutter_segment: ^2.0.2
  translator: ^0.1.4
  file_picker: ^1.3.6
  path_provider: ^1.5.1
  flutter_cupertino_localizations:
  easy_localization: ^1.3.1
  fancy_shimmer_image: ^1.0.0+1
  json_to_form: ^0.0.4
  font_awesome_flutter: ^8.7.0
  flutter_statusbarcolor: ^0.2.3
  url_launcher: ^5.4.2
  flutter_datetime_picker:  
  overlay_support: ^1.0.5
  #geolocator: ^5.3.1
  geocoder: ^0.2.1
  location: ^3.0.2
  webview_flutter: ^0.3.22+1
  add_2_calendar: ^1.4.0
  rename: ^1.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.0
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/appicon/icon_ios.png"
  image_path_android: "assets/appicon/icon_android.png"
  adaptive_icon_background: "assets/appicon/icon_back.png"
  adaptive_icon_foreground: "assets/appicon/icon_front.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight : 600

  assets:
    - assets/lottie/bouncing_white.json
    - assets/lottie/bouncing_white1.json
    - assets/lottie/bouncing.json
    - assets/img/0.png
    - assets/img/notifications-button-black.png
    - assets/img/imgHome.png
    - assets/img/imghome2.png
    - assets/img/dummyProfilePic.png
    - assets/img/loginscreenbackground.png
    - assets/img/headerProfile.png
    - assets/img/womanface.jpg
    - assets/img/notifications-button.png
    - assets/avatars/avatar-1.jpg
    - assets/imgIllustration/IlustrasiMessage.png
    - assets/imgIllustration/IlustrasiOnBoarding1.png
    - assets/imgIllustration/IlustrasiOnBoarding2.png
    - assets/imgIllustration/IlustrasiOnBoarding3.png
    - assets/imgIllustration/IlustrasiCart.png
    - assets/language/en-US.json
    - assets/language/zh-HK.json
    - assets/language/ar-DZ.json
    - assets/language/hi-IN.json
    - assets/language/id-ID.json
    - assets/icon/truck.png
    - assets/icon/hiking.png
    - assets/icon/chat.png
    - assets/icon/notification.png
    - assets/icon/search.png
    - assets/icon/research.png
    - assets/icon/callcenter.png
    - assets/icon/setting.png
    - assets/icon/aboutapp.png
    - assets/icon/shopping-cart.png
    - assets/icon/message.png
    - assets/img/step-1.png
    - assets/img/step-2.png
    - assets/img/step-3.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
